Add asdf related stuff to the bin/setup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -2,6 +2,25 @@
 
 set -e
 
+echo "[setup]: Installing required languages"
+if command -v asdf &>/dev/null; then
+  set +e
+  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git 2>/dev/null
+  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git 2>/dev/null
+  set -e
+
+  asdf install
+
+  gem install bundler
+else
+  echo "
+    We are using asdf (https://github.com/asdf-vm/asdf) to manage tool
+    dependencies, since it was not found on your system we cannot ensure that you
+    are using the correct versions of all the tools. Please install it and run
+    this script again, or proceed at your own peril.
+  "
+fi
+
 cp .env.sample .env
 
 bundle check || bundle install
