Add asdf related stuff to the bin/setup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -2,10 +2,34 @@
 
 set -e
 
+echo "[setup]: Installing required languages"
+if [ -x "$(command -v asdf)" ]; then
+  set +e
+  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git 2>/dev/null
+  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git 2>/dev/null
+  set -e
+
+  asdf install
+
+  echo "[setup]: Installing bundler"
+
+  gem install bundler
+else
+  echo "
+    We are using asdf (https://github.com/asdf-vm/asdf) to manage tool
+    dependencies, since it was not found on your system we cannot ensure that you
+    are using the correct versions of all the tools. Please install it and run
+    this script again, or proceed at your own peril.
+  "
+fi
+
+echo "[setup] Setting up .env file"
 cp .env.sample .env
 
+echo "[setup]: Installing dependencies with bundler"
 bundle check || bundle install
 
+echo "[setup]: Preparing database"
 bundle exec rake db:create || true
 bundle exec rake db:migrate
 bundle exec rake db:seed
